name: Build Container
run-name: Build Container

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'src/**'
    branches:
      - 'dev'
  release:
    types: [published]

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      image_name: mguyard/fortinet-pricelist-web
      platforms: linux/amd64,linux/arm64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.registry }}/${{ env.image_name }}
          tags: |
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' }}
            type=raw,value=dev-{{branch}}-{{sha}},enable=${{ github.event_name != 'release' }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test Image
        run: |
          # Utilisez le premier tag généré par l'étape metadata
          IMAGE_TO_TEST=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "Testing image: $IMAGE_TO_TEST"
          
          # Lancer le conteneur en arrière-plan
          docker run -d --name test-container -p 3000:3000 -v /tmp/data:/data $IMAGE_TO_TEST
          
          # Attendre que le conteneur soit prêt (ajustez le temps si nécessaire)
          echo "Waiting for container to start..."
          sleep 20
          
          # Vérifier si le conteneur est en cours d'exécution
          if ! docker ps | grep -q test-container; then
            echo "Container failed to start"
            docker logs test-container
            exit 1
          fi
          
          # Tester l'accès à l'application
          echo "Testing application access..."
          response=$(curl -k -s -o /dev/null -w "%{http_code}" https://localhost:3000 --max-time 10)
          echo "Received HTTP status code: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "Test passed: Received HTTP 200"
          else
            echo "Test failed: Received HTTP $response"
            docker logs test-container
            exit 1
          fi
          
          # Arrêter et supprimer le conteneur
          docker stop test-container && docker rm test-container



      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max