name: Create Release
run-name: Create Release on tag creation

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history so we can generate changelog

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ACTION_PERSONAL }}
          draft: false
          prerelease: false
          generate_release_notes: true